<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Customerprice
 * @copyright Copyright (c) 2017 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
?>
<div class="admin__field-complex">
    <span class="title"><?= /* @noEscape */ $block->getHeaderText() ?></span>
    <?php if ($block->getButtonsHtml()): ?>
        <div class="admin__field-complex-elements"><?= /* @noEscape */ $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>
<?= /* @noEscape */ $block->getChildHtml('', true) ?>