<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Customerprice
 * @copyright Copyright (c) 2017 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
if ($block->getmoduleStatus()) {
    ?>
<li>  
   <a <?= /* @noEscape */ $block->getLinkAttributes() ?>><?= /* @noEscape */ $block->escapeHtml($block->getLabel())?>  
     <?= /* @noEscape */($block->getCounter()) ? '<span class="counter qty">' .
        $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>
   </a>  
 </li>  
<?php } ?>