<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Customerprice
 * @copyright Copyright (c) 2017 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
?>
<div class="page-create-order">
    <div>
        <div id="order-search-category" style="display: none;" class="admin__page-section order-search-items">
            <?= /* @noEscape */ $block->getChildHtml('searchcategory') ?>
        </div>
        <section id="order-items-category" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?= /* @noEscape */ $block->getChildHtml('itemscategory') ?>
        </section>
    </div>
</div>