<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Customerprice
 * @copyright Copyright (c) 2017 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
?>
<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid
 */
?>

<?php $_items = json_decode($block->getOptionValues());
 
?>
<?php if (empty($_items)): ?>
    <form id="edit_form" data-form="edit_form" method="post" enctype="multipart/form-data" >
        <div id="order-items_grid">
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-tables" id="attribute-options-table-category">
                    <thead>
                        <tr class="headings">
                            <th class="col-product"><span><?= /* @noEscape */ __('Category ID') ?></span></th>
                            <th class="col-product-name"><span><?= /* @noEscape */ __('Category Name') ?></span></th>
                            
                            <th class="col-special-price"><span><?= /* @noEscape */ __('Discount') ?></span></th>
                            <th class="col-action"><span><?= /* @noEscape */ __('Action') ?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="even" id="no-product">
                            <td class="empty-text" colspan="100">
                                <?= /* @noEscape */ __('No Category selected') ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <input type="hidden" data-form-part="customer_form" id="option-count-check" value="" />
                <input type="hidden" data-form-part="customer_form" name="customer_id"
                       value="<?= /* @noEscape */ $block->getRequest()->getParam("id") ?>" />
            </div>
        </div>
    </form>
<?php else: ?>
    <form id="edit_form" data-form="edit_form" method="post" enctype="multipart/form-data" >
        <div id="order-items_grid">
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-tables" id="attribute-options-table-category">
                    <thead>
                        <tr class="headings">
                            <th class="col-product"><span><?= /* @noEscape */ __('Category ID') ?></span></th>
                            <th class="col-product-name">
                                <span>
                                    <?= /* @noEscape */ __('Category Name') ?>
                                </span>
                            </th>
                            <th class="col-special-price"><span><?= /* @noEscape */ __('Discount') ?></span></th>
                            <th class="col-action"><span><?= /* @noEscape */ __('Action') ?></span></th>
                        </tr>
                    </thead>

                    <?php $i = 0 ?>

                    <tbody class="<?= /* @noEscape */ ($i % 2) ? 'even' : 'odd' ?>">

                        <tr class="even" id="no-product" style="display:none">
                            <td class="empty-text" colspan="100"><?= /* @noEscape */ __('No product selected') ?></td>
                        </tr>

                        <?php
                        //$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        //$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                        ?>
                        <?php foreach ($_items as $_item):$i++ ?>
                            <tr class="option-row " id = "category-row-<?= /* @noEscape */ $_item->id ?>">
                                <td>
                                    <span><?= /* @noEscape */ $_item->pid ?></span>
                                    <input type="hidden" data-form-part="customer_form"
                                           name="categoryoption[value][<?= /* @noEscape */ $_item->id ?>][pid]"
                                           value="<?= /* @noEscape */ $_item->pid ?>" />
                                </td> 
                                <td>
                                    <span><?= /* @noEscape */ $_item->pname ?></span>
                                    <input type="hidden" data-form-part="customer_form"
                                           name="categoryoption[value][<?= /* @noEscape */ $_item->id ?>][pname]"
                                           value="<?= /* @noEscape */ $_item->pname ?>" />
                                </td> 
                                
                                <td>
                                    <input style="width:50%;" data-form-part="customer_form"
                                           data-form-part="customer_form"
                                           class="required-entry validate-zero-or-greater
                                           input-text admin__control-text required-entry _required
                                           validate-number validate-digits-range digits-range-0-100"
                                           type="text" name="categoryoption[value]
                                           [<?= /* @noEscape */ $_item->id ?>][discount]"
                                           value="<?= /* @noEscape */ $_item->discount ?>"> &nbsp; <strong>%</strong>
                                </td>  
                                <td id="delete_button_container_<?= /* @noEscape */ $_item->id ?>">
                                    <input type="hidden" data-form-part="customer_form" class="delete-flag"
                                           name="categoryoption[value][<?= /* @noEscape */ $_item->id ?>][cid]"
                                           value="<?= /* @noEscape */ $block->getRequest()->getParam("id") ?>" />
                                    <button class="delete-option delete-category-save"
                                            rel="<?= /* @noEscape */ $_item->id ?>"
                                            type="button"><span>Remove Category</span></button>
                                </td> 
                            </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
                <input type="hidden" data-form-part="customer_form" id="option-count-check" value="" />
                <input type="hidden" data-form-part="customer_form" name="customer_id"
                       value="<?= /* @noEscape */ $block->getRequest()->getParam("id") ?>" />

            </div>
        </div>
    </form>
<?php endif; ?>


